In [62]:
import pandas as pd
from sklearn import model_selection
from sklearn import linear_model
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [ ]:
#define the data path
Learn_Data_Path = './US_Census_Data/census_income_learn.csv'
Test_Data_Path  = './US_Census_Data/census_income_test.csv'

In [32]:
Train_Data_Set = pd.read_csv(Learn_Data_Path,sep=',', header=None, index_col=False)
Test_Data_Set = pd.read_csv(Test_Data_Path,sep=',', header=None, index_col=False)

In [33]:
Train_Data_Set

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
5,48,Private,40,10,Some college but no degree,1200,Not in universe,Married-civilian spouse present,Entertainment,Professional specialty,...,Philippines,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,95,- 50000.
6,42,Private,34,3,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
7,28,Private,4,40,High school graduate,0,Not in universe,Never married,Construction,Handlers equip cleaners etc,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,30,95,- 50000.
8,47,Local government,43,26,Some college but no degree,876,Not in universe,Married-civilian spouse present,Education,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
9,34,Private,4,37,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
10,8,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
11,32,Not in universe,0,0,High school graduate,0,Not in universe,Never married,Not in universe or children,Not in universe,...,?,?,?,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
12,51,Private,4,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
13,46,Private,37,31,High school graduate,0,Not in universe,Divorced,Business and repair services,Other service,...,Columbia,Columbia,Columbia,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,- 50000.
14,26,Private,24,12,Bachelors degree(BA AB BS),0,Not in universe,Never married,Manufacturing-nondurable goods,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
15,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
16,47,Private,39,36,Bachelors degree(BA AB BS),0,Not in universe,Never married,Personal services except private HH,Machine operators assmblrs & inspctrs,...,Germany,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
17,39,Not in universe,0,0,10th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,0,94,- 50000.
18,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,United-States,El-Salvador,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
19,35,Private,12,41,High school graduate,0,Not in universe,Married-civilian spouse present,Manufacturing-durable goods,Handlers equip cleaners etc,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,49,95,- 50000.
20,12,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
21,27,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,1,Not in universe,2,52,94,- 50000.
22,56,Private,35,22,Some college but no degree,500,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,32,95,- 50000.
23,46,Private,45,12,Masters degree(MA MS MEng MEd MSW MBA),0,Not in universe,Married-civilian spouse present,Other professional services,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
24,55,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Japan,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,94,- 50000.
25,2,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
26,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,?,?,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
27,37,Private,3,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Mining,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
28,4,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
29,37,Private,4,2,Bachelors degree(BA AB BS),0,Not in universe,Never married,Construction,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199493,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
199494,5,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
199495,44,Self-employed-not incorporated,38,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,94,- 50000.
199496,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
199497,40,Self-employed-not incorporated,35,17,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,95,- 50000.
199498,50,Private,42,26,High school graduate,0,Not in universe,Married-civilian spouse present,Medical except hospital,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
199499,59,Private,24,2,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,50000+.
199500,74,State government,44,42,7th and 8th grade,0,Not in universe,Widowed,Social services,Handlers equip cleaners etc,...,?,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
199501,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
199502,50,Federal government,29,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Transportation,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,48,95,- 50000.
199503,24,Private,33,29,11th grade,0,Not in universe,Never married,Retail trade,Other service,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,95,- 50000.
199504,43,Private,22,36,High school graduate,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Machine operators assmblrs & inspctrs,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,52,95,- 50000.
199505,33,Private,34,3,High school graduate,0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
199506,14,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
199507,25,Self-employed-incorporated,33,16,Some college but no degree,0,Not in universe,Never married,Retail trade,Sales,...,?,?,?,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,94,- 50000.
199508,62,Private,4,2,Some college but no degree,0,Not in universe,Married-spouse absent,Construction,Executive admin and managerial,...,Greece,United-States,United-States,Native- Born in the United States,2,Yes,1,52,95,50000+.
199509,47,Local government,43,12,Doctorate degree(PhD EdD),0,Not in universe,Married-civilian spouse present,Education,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,94,50000+.
199510,25,Private,33,41,Some college but no degree,0,Not in universe,Never married,Retail trade,Handlers equip cleaners etc,...,United-States,Germany,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
199511,47,Private,23,37,Some college but no degree,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
199512,71,Not in universe,0,0,High school graduate,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
199513,57,Private,9,37,9th grade,0,Not in universe,Divorced,Manufacturing-durable goods,Machine operators assmblrs & inspctrs,...,Dominican-Republic,Dominican-Republic,Dominican-Republic,Foreign born- Not a citizen of U S,0,Not in universe,2,52,95,- 50000.
199514,51,Private,33,19,10th grade,0,Not in universe,Widowed,Retail trade,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
199515,87,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,?,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
199516,3,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
199517,39,Private,43,26,Bachelors degree(BA AB BS),0,Not in universe,Never married,Education,Adm support including clerical,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,2,Not in universe,2,52,95,- 50000.
199518,87,Not in universe,0,0,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Canada,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
199519,65,Self-employed-incorporated,37,2,11th grade,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
199520,47,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Poland,Poland,Germany,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,95,- 50000.
199521,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
199522,32,Private,42,30,High school graduate,0,Not in universe,Never married,Medical except hospital,Other service,...,?,?,?,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,- 50000.

In [4]:
Test_Data_Set

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,38,Private,6,36,1st 2nd 3rd or 4th grade,0,Not in universe,Married-civilian spouse present,Manufacturing-durable goods,Machine operators assmblrs & inspctrs,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,12,95,- 50000.
1,44,Self-employed-not incorporated,37,12,Associates degree-occup /vocational,0,Not in universe,Married-civilian spouse present,Business and repair services,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,26,95,- 50000.
2,2,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
3,35,Private,29,3,High school graduate,0,Not in universe,Divorced,Transportation,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,94,- 50000.
4,49,Private,4,34,High school graduate,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,95,- 50000.
5,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,Germany,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
6,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,Mexico,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
7,61,Not in universe,0,0,High school graduate,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
8,38,Private,45,12,Masters degree(MA MS MEng MEd MSW MBA),0,Not in universe,Married-civilian spouse present,Other professional services,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
9,7,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
10,30,Private,30,26,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Communications,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
11,85,Not in universe,0,0,10th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
12,33,Private,36,27,High school graduate,0,Not in universe,Married-civilian spouse present,Private household services,Private household services,...,Trinadad&Tobago,Trinadad&Tobago,Trinadad&Tobago,Foreign born- Not a citizen of U S,0,Not in universe,2,30,94,- 50000.
13,26,Private,33,29,Some college but no degree,425,Not in universe,Never married,Retail trade,Other service,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,17,94,- 50000.
14,46,Private,37,21,High school graduate,0,Not in universe,Married-civilian spouse present,Business and repair services,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
15,19,Private,33,26,Some college but no degree,0,College or university,Never married,Retail trade,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
16,11,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,Mexico,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
17,23,Private,45,26,Bachelors degree(BA AB BS),0,College or university,Married-civilian spouse present,Other professional services,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
18,27,Private,37,31,High school graduate,0,Not in universe,Married-civilian spouse present,Business and repair services,Other service,...,?,?,?,Foreign born- Not a citizen of U S,1,Not in universe,2,50,94,- 50000.
19,35,Self-employed-not incorporated,4,2,High school graduate,0,Not in universe,Divorced,Construction,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,50000+.
20,8,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
21,29,Not in universe,0,0,High school graduate,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,94,- 50000.
22,40,Private,42,2,Some college but no degree,0,Not in universe,Divorced,Medical except hospital,Executive admin and managerial,...,?,?,?,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,95,- 50000.
23,24,Private,33,16,High school graduate,0,Not in universe,Married-civilian spouse present,Retail trade,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
24,45,Private,33,16,Some college but no degree,930,Not in universe,Married-civilian spouse present,Retail trade,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
25,27,Private,40,23,Some college but no degree,0,Not in universe,Never married,Entertainment,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
26,41,Local government,47,28,High school graduate,0,Not in universe,Married-civilian spouse present,Public administration,Protective services,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
27,14,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
28,73,Not in universe,0,0,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,?,?,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
29,46,Private,32,33,Some college but no degree,0,Not in universe,Married-civilian spouse present,Wholesale trade,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,36,94,- 50000.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99732,54,Private,45,12,Masters degree(MA MS MEng MEd MSW MBA),0,Not in universe,Married-civilian spouse present,Other professional services,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,30,94,- 50000.
99733,0,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
99734,45,Not in universe,0,0,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Mexico,Mexico,Mexico,Foreign born- U S citizen by naturalization,0,Not in universe,2,0,94,- 50000.
99735,45,Private,40,31,High school graduate,1026,Not in universe,Married-civilian spouse present,Entertainment,Other service,...,Philippines,Philippines,Philippines,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,95,- 50000.
99736,30,Private,33,16,Bachelors degree(BA AB BS),1200,Not in universe,Never married,Retail trade,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
99737,73,Not in universe,0,0,10th grade,0,Not in universe,Never married,Not in universe or children,Not in universe,...,Italy,Italy,United-States,Native- Born in the United States,0,Not in universe,2,1,94,- 50000.
99738,4,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
99739,5,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
99740,40,Private,37,26,High school graduate,0,Not in universe,Married-civilian spouse present,Business and repair services,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,1,Not in universe,2,48,95,- 50000.
99741,52,Federal government,34,26,High school graduate,0,Not in universe,Widowed,Finance insurance and real estate,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99742,20,Private,2,44,High school graduate,0,Not in universe,Never married,Agriculture,Farming forestry and fishing,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,26,95,- 50000.
99743,7,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
99744,55,Private,34,17,Masters degree(MA MS MEng MEd MSW MBA),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99745,75,Not in universe,0,0,Bachelors degree(BA AB BS),0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,Canada,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
99746,0,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
99747,57,Private,24,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99748,22,Private,40,44,Some college but no degree,0,Not in universe,Never married,Entertainment,Farming forestry and fishing,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,27,95,- 50000.
99749,48,Private,35,26,High school graduate,0,Not in universe,Divorced,Finance insurance and real estate,Adm support including clerical,...,United-States,?,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
99750,23,Not in universe,0,0,High school graduate,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,England,England,England,Foreign born- Not a citizen of U S,0,Not in universe,2,0,94,- 50000.
99751,22,Private,43,26,Some college but no degree,0,College or university,Never married,Education,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
99752,46,Private,44,3,Some college but no degree,0,Not in universe,Married-civilian spouse present,Social services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99753,2,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
99754,17,Private,33,29,10th grade,0,High school,Never married,Retail trade,Other service,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,1,95,- 50000.
99755,20,Not in universe,0,0,Some college but no degree,0,College or university,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
99756,4,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
99757,14,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,- 50000.
99758,61,Private,8,36,11th grade,0,Not in universe,Separated,Manufacturing-durable goods,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99759,24,Self-employed-not incorporated,1,43,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Agriculture,Farming forestry and fishing,...,Mexico,Mexico,Mexico,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,94,- 50000.
99760,30,Private,45,2,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Other professional services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99761,67,Not in universe,0,0,9th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,94,- 50000.

In [34]:
# Naming the columns :
columns = ['AAGE', 'ACLSWKR', 'ADTIND', 'ADTOCC', 'AHGA', 'AHRSPAY',         
           'AHSCOL', 'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN',      
           'ASEX', 'AUNMEM', 'AUNTYPE', 'AWKSTAT', 'CAPGAIN', 'CAPLOSS',     
           'DIVVAL', 'FILESTAT', 'GRINREG', 'GRINST', 'HHDFMX', 'HHDREL',    
           'MARSUPWT', 'MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 
           'NOEMP', 'PARENT', 'PEFNTVTY', 'PEMNTVTY', 'PENATVTY', 'PRCITSHP',
           'SEOTR', 'VETQVA', 'VETYN', 'WKSWORK', 'YEAR', 'WAGE']

In [35]:
Train_Data_Set.columns=columns

Test_Data_Set.columns=columns

In [36]:
Test_Data_Set.tail(2)

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,WAGE
99760,30,Private,45,2,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Other professional services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,- 50000.
99761,67,Not in universe,0,0,9th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,94,- 50000.

In [37]:
#remove the unwanted information for classification

Train_Data_Set.drop(['MARSUPWT', 'MIGMTR1','GRINREG', 'GRINST','AUNMEM','HHDFMX', 'HHDREL','FILESTAT',
                     'PEFNTVTY', 'PEMNTVTY', 'PENATVTY','AREORGN','ADTIND', 'ADTOCC','SEOTR','YEAR',
                     'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN','VETQVA', 'VETYN','AUNTYPE'], axis=1, inplace=True)
Test_Data_Set.drop(['MARSUPWT', 'MIGMTR1', 'MIGMTR3', 'GRINREG', 'GRINST','AUNMEM','HHDFMX', 'HHDREL','FILESTAT',
                    'PEFNTVTY', 'PEMNTVTY', 'PENATVTY','AREORGN','ADTIND', 'ADTOCC','SEOTR','YEAR',
                    'MIGMTR4', 'MIGSAME', 'MIGSUN','VETQVA', 'VETYN','AUNTYPE'], axis=1, inplace=True)

In [38]:
list(Test_Data_Set)

['AAGE',
 'ACLSWKR',
 'AHGA',
 'AHRSPAY',
 'AHSCOL',
 'AMARITL',
 'AMJIND',
 'AMJOCC',
 'ARACE',
 'ASEX',
 'AWKSTAT',
 'CAPGAIN',
 'CAPLOSS',
 'DIVVAL',
 'NOEMP',
 'PARENT',
 'PRCITSHP',
 'WKSWORK',
 'WAGE']

In [39]:
Train_Data_Set.dtypes

AAGE         int64
ACLSWKR     object
AHGA        object
AHRSPAY      int64
AHSCOL      object
AMARITL     object
AMJIND      object
AMJOCC      object
ARACE       object
ASEX        object
AWKSTAT     object
CAPGAIN      int64
CAPLOSS      int64
DIVVAL       int64
NOEMP        int64
PARENT      object
PRCITSHP    object
WKSWORK      int64
WAGE        object
dtype: object

In [40]:
def annual_wage(df):
    wage = []
    for w in df['WAGE']:
        if w == ' - 50000.':
            wage.append(0)
        else:
            wage.append(1)
    return wage

In [41]:
Test_Data_Set.insert(0, 'WAGE_ANN', int)
Train_Data_Set.insert(0, 'WAGE_ANN', int)

In [43]:
Train_Data_Set['WAGE_ANN'] = annual_wage(Train_Data_Set)
Test_Data_Set['WAGE_ANN'] = annual_wage(Test_Data_Set)

In [44]:

Train_Data_Set.drop(['WAGE'], axis=1, inplace=True)
Test_Data_Set.drop(['WAGE'], axis=1, inplace=True)

In [51]:
def dummy_variables(df):
    df_type = df.dtypes
    for col in df_type.keys():
        if df_type[col] == 'object':
            df = pd.concat([df, pd.get_dummies(df[col]).rename(columns=lambda x: col + '_' + str(x))], axis=1)
            df.drop([col], axis=1, inplace=True)
    return df

trainset_ = dummy_variables(Train_Data_Set)
testset_ = dummy_variables(Test_Data_Set)

In [59]:
X = trainset_.iloc[:,1:]
Y = trainset_['WAGE_ANN']

In [60]:
X_train, X_val, Y_train, Y_val = model_selection.train_test_split(X, Y, \
                                                                  test_size=0.20, random_state=100)

In [63]:
logregCV = linear_model.LogisticRegressionCV()
logregCV.fit(X_train, Y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [64]:
Y_pred = logregCV.predict(X_val)

In [67]:
print ('Accuracy score : %.3f' %(logregCV.score(X_val, Y_val)))

Accuracy score : 0.951